name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t ghcr.io/divanomni/ada_python/ada_python/python-app:latest .

    - name: Authenticate to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker Image to GitHub Package Registry
      run: docker push ghcr.io/divanomni/ada_python/ada_python/python-app:latest

    - name: run ssh
      run: ssh -o 'divanomni-adapython-eo0ytz6orhg#H7rKbDOCoDRpe8qwkPIhRJFjAKhKi0GF@divanomni-adapython-eo0ytz6orhg.ssh.ws-eu106.gitpod.io' 'cd/workspace/ada_python && docker compose pull && docker compose up -d' 
      
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Authenticate to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Pull Docker Image from GitHub Package Registry
      run: docker pull ghcr.io/divanomni/ada_python/ada_python/python-app:latest

    - name: Run Docker Container
      run: docker run -d -p 8080:80 ghcr.io/divanomni/ada_python/ada_python/python-app:latest
